#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

importar = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wUYFTI2StZUKQAAABl0RVh0Q29tbWVudABD"
    "cmVhdGVkIHdpdGggR0lNUFeBDhcAAAoFSURBVGje7ZlrjFxnecd/73vOzOzO7s56d7NX41ww"
    "ENPYa5yQBByHD2kBhSIFJD6AQAJFRU0r1KhVKyEoEKdClCoKMhfjJIqxEEECpNCCgCQqlxAH"
    "CCLxh5ISO7HXl3jtvdkzO5dzeS9PP5yzs7v1bbNeCSH8SqMzZ+Y9Z/7/5/J/nvMMXFlX1pX1"
    "J73UWt7s01/49l/rQN/VWym/p1AIrFYKFGilMNbinSc2BhEJ5+ejH0et5L++/PmP/+iPQuAf"
    "PrOv681vHFtvrL2r0t35H+VyidHhPkrFAsVQo7TCe0HEI14QAS8e5z1RlFBvRszXm5yerhIn"
    "hiS1e7zzX5+vR0fed+tbm39111tlzQns2vsTde/dd8qXHvnRR0aG+j7W3VX6y6sGKnQUQ0QE"
    "5xzOC957vHhEBPGCbx/zz0RABAGc9zSbEdV6k1NTZ4mi+Gnn2P/FT9/9rwD3/PNX2fPAJy6f"
    "wFf3Pak+8bF3y1f2PfnEpjeMvaunp1NpyMEK4jPriuQEvLTBOu8R79te8O19OTEE7zzWWaZm"
    "zjJXrZPE9uzUyfrWb+75pxOf3PkQ//65v718D+z+5lNPXP+GsXeXO0oIOeAFi+dEFsFm4OzC"
    "d87jnCc1Bucc1nqEjFQQaAAEQQGnp89QjyKJmjYuerfpi/f//fELYQpXCv7zux7fcc2GwXeI"
    "CNbZNlDnMmtnls1i3jpHmlpSY0iNwaSW1GTnPifs8jDzLiMIGZFCGCKAd16FRTobdfMB4MHL"
    "JjA5ddZucdeY1JhOrRXOubblxQvGOZIkJU5SrHVY5/I9mVdcDrKdAwj4PBcky5PUWFok7fta"
    "64nitHIxXCsmMDbSz6uTc4yM9GKtAwRrPdY6kjRdQkhwfun7BZIL3lpu+cwTWS4Ji+HovJAk"
    "FmsvLkYrJjAy3MfQQIWztQbOWzo7CjjnF8HKhcH7i4KXdv4sJLexniSxiAjlcrg2BJLU0NPT"
    "ychQH9Vagz+8fIJyOaQQBlkiu1WCdx5PpmJehPn5FK2FQkGBUsTNNfJALhMEgebaq4e5aXwj"
    "Lx+e5JWjkzSTCB1kmu6sxzmHkEvo/wPvvM/rBe3PjbG0okwYyuWgLY5ZrrCGBBZ4iBCnhhve"
    "vIFbtm0kTgyvTJxmZq5Kdb5BoxURxSlpanAuBVF4p/CiEFGICtFaQAVEUYQxho5ODQSIvDYs"
    "4eX0IM55jPUUCyFXrx9gXW8njWbUfrWimFaSkiSGJDWkxmKcw+Y1IWstUkT0awa+sPRKNxrj"
    "LhVdSyQSdKAJAk2YH4NAo7VCa4VS+f78dckbrwWBlw9PUq01CbReaZwRKI26jIZXvBBFdm0I"
    "jG++lnozZvZMvV36LxqbOuSVueMkcYxaJYdWy9F5CRldMQFrHdduGGS+0eL4yRmS1KLgAuAU"
    "h2aP8P36Qzx08OtMT5/OQ0tdMiREwBhPs2Hp7imsXQ6QJ+3rrx6mp6vM1NRZjp+c5eiJGZLU"
    "EGiN1ppCEPJqdZKf1L7FwDAMbp7nx3PfZ3rqFCp/wIEsDxZeWY550tRjUo9C0dUTrrWMZj/u"
    "xdNbKdNd7iAMFZ3FAkdfnaFabRDHllO1ab5b20W5P0ahCLSid3OVHz7/OO8176cyNEiapjQa"
    "MdZ5Gs0UYxzFks4JqRUl7yUJPPDAA/3btr2lIt6LUviTZ+xImkQ6DkFjUT7NnrzKHawf7Kav"
    "p8D/vnqUbx/ZRd9IgveLsRVozXXbU/5z/3e5eeYORkfH6K0UAaEYptSbBusFpfRrzpMLEigW"
    "iw+OjF3z0dRkKjAwlIu/gDcJDWf4w4v/w5bxcawRjswc59HDX6ZnQ4r35wJxBq671XPy4HO8"
    "a+Pf8PrrNiIIQRDwm9/8ml8cOEJf/8A5ErrUEK8pB1RQjFTHIKlUSKVCIhUSnx1TejFqHbrQ"
    "TaE8ykQ15pETX6NytUFfxIoKRen6OrsP7eXQK7M0bTcN00ViA6xNz1sCmtEqe6E4dbw0MUe9"
    "Pn9+MDqgXm3x+8Oz7D60k7GNCc6pFWSSYmBLjS/98kE+OPd3dF81QK0eLcb+EjVqNR2lUrA6"
    "AvP1Bk/8Yj/NRv28pcgDQ50pvzw0Sc+NCS4v1EpBbAUbC11dmTcaTU+5S6EX7mQVMjTLd773"
    "GOvftJX+UoNA67YiJYnHWaFU0ji3Sg/0dAbccsMozg2dtw9SSjF1epJ3jmzga8eeoWdgHrxi"
    "PnYce7zB8I5OurozAtEpy9FJy/gdZfCgC4r5lyxvGytyx20bmJyc5IXDU7Sa2bNyR0dAR2fQ"
    "rj+rIrCut8J773znRS/ev38/O3bsoP+3Ff7lB/cjlQh7ALZ0XEe1NLeYaIHmxumNTPz0DLyu"
    "Qf2g442nhrn5zpu4/bZbefqZZ6n97gS9vZpy12JHupIG75J1QPKRiSw5B9Bat5+kxm/YzM6z"
    "/8izzzyLvEno33AVPy88BZJmxdd7+gf7ef/Nd/HC8wdo6gZj29dz/aZNhGEIIvT0hoQFtfbt"
    "tFIKFQTLCYmg88qrlaJQLHLrjrdx/eZNRK0WkUp5+sB/L1ETwVnLX2zdzJZtW6nX5ymWSqxb"
    "t45SqQRKrbqdviCBRqPBr371LM75ZeDbYaE1ExMTiIBzdvF7pagldax1FJdcd+r0KV54/gUG"
    "BvrwPtt34vhxlNLMTM+gtTpvL+2dXR2B7u5utm+/7Rzwko8EA60REW6/fQfGmGV7ZuqzPPaz"
    "vYBpe3HwqiG23biNsdHR3IvZ/iAMOFOt4V+aPEcpvBXxUf3oqggsGDs1pn2yAB7Aa43zHmMM"
    "SZIiknnKe0+cJMt7GQHrHFEU0Wy12rMgAYIgaBtgadga42nMzj65b/fOfaurxOo8s0eVP55I"
    "vkEEpdQy72QXqovOMLNJnGq/V4tdCt57Wo242pya/Ny+3Tvv/Og9n1Grq8RxzOHDh9tDrKXW"
    "FEBrRbVaZWJiAmvMMoOfjWp4cctagjiJmZ6aWgSdW0grRavVIolTlzZav49j863JQ1OPPPnE"
    "rtrd93yKvXv+TVbXzBUKjI6OYq0hmwrKMkvrIODYsWMMDQ2RpGnOMRtO0dRoCihlQIGtCT1d"
    "Ffr6+1nX23uOGHR3lRthPPehtBo8842Hv1AD+PDH72fvns+uXoWU1nR0dJAk+eRYFtXIixDo"
    "gCAIKJVK7XzJQkMY0P1ske08d/IpamcM4YEORrYNUe7spFAoLDeEDigWC/7tt4zP3nvvvbWF"
    "33jskc9enowqpUKtNWEY5D+o20PYQMgnDJowCAkCg0jWzwtQ1JqP3PQ+ij+A55/7LW8Z38L4"
    "1nG6urrRQQD5fZRkHgA6rLV6TevAzMzMzx5++GFExJ4z4ciTt9FocPDgwfZ4/JwKnqYMDw8y"
    "36zz4osvcvToMbRWebRJW3FarVY8ODh4as3+rLvvvvv+KP84Pvroo1f+dr2yrqw/t/V/sZPB"
    "jEHQ2LEAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
libro = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAIASURBVDjLpVPPaxNREJ6Vt01c"
    "aH4oWk1T0ZKlGIo9RG+BUsEK4kEP/Q8qPXnpqRdPBf8A8Wahhx7FQ0GF9FJ6UksqwfTSBDGy"
    "B5HkkphC9tfb7jfbtyQQTx142byZ75v5ZnZWC4KALmICPy+2DkvKIX2f/POz83LxCL7nrz+W"
    "PNcll49DrhM9v7xdO9JW330DuXrrqkFSgig5iR2Cfv3t3gNxOnv5BwU+eZ5HuON5/PMPJZKJ"
    "+yKQfpW0S7TxdC6WJaWkyvff1LDaFRAeLZj05MHsiPTS6hua0PUqtwC5sHq9zv9RYWl+nu5c"
    "ETcnJ1M0M5WlWq3GsX6/T+VymRzHDluZiGYAAsw0TQahV8uyyGq1qFgskm0bHIO/1+sx1rFt"
    "chJhArwEyIQ1Gg2WD2A6nWawHQJVDIWgIJfLhQowTIeE9D0mKAU8qPC0220afsWFQoH93W6X"
    "7yCDJ+DEBeBmsxnPIJVKxWQVUwry+XyUwBlKMKwA8jqdDhOVCqVAzQDVvXAXhOdGBFgymYwr"
    "GoZBmUyGjxCCdF0fSahaFdgoTHRxfTveMCXvWfkuE3Y+f40qhgT/nMitupzApdvT18bu+YeD"
    "QwY9Xl4aG9/d/URiMBhQq/dvZMeVghtT17lSZW9/rAKsvPa/r9Fc2dw+Pe0/xI6kM9mT5vtX"
    "y+Nw2kU/5zOGRpvuMIu0YAAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
libro_azul = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAKnRFWHRDcmVhdGlvbiBUaW1l"
    "AFNhIDkgRmViIDIwMDIgMTY6MDE6NTEgKzAxMDCR21o5AAAAB3RJTUUH1AcHCBsvZni3SwAA"
    "AAlwSFlzAAAK8AAACvABQqw0mAAAAARnQU1BAACxjwv8YQUAAAKaSURBVHjajZNLTBNRFIb/"
    "mU4pM51pKYGKYBEoLwUTiVB8YGJdGCOJibjSmOhOF+40Llzo1o1rE3cu3Gh0QQI+IsZIIMRI"
    "eIUEUyDlUdMWCpTOq0zb8Qy2BjGiN/kzd3LP958zZ85lsPdiduzNfwXQ/gWLK7ZmpJgAeGcH"
    "JNcxaJsq+u9fR3I0RjHpPw1uL50FY1yAVNwOh9oG8C6wPKBqYKEjZ3LA1Mc36Lt1j/jQbhOb"
    "79Kd8QrJDKZ8B2qE+KrjiJhGwKWg+5AdPS0Cosk0YvA2gPdLWHg7QUyKlCsYsEsbGmMvLYV3"
    "NQI9yyDY4kRzjYQSnsO6BhytFgGOqqg/dQ1tD24SU0niflUA7/kzRmer3zG3CMXpRjQmYzqW"
    "xetJBYPjSUx8SwC6Qi0kd8kXgMGtYG1slljVaqwN9qaELvqvFjfVMdLyHMIyZaaykSaZW0DW"
    "ADKZn++5HAu+9gS05Dzk2TAZaCymHg5i5FN/nM501g4PR5BBwYYFEZzOAjI945QwkkBbpSYw"
    "TLaV4FpSEbddSmj4EQYbziWDnXbP0DDB9BesBsgp7HOt43iVgpNBGzobBfh8Far/2XsHcU6r"
    "h9x2RyNPRjF1+HnG33RDmx9DwKuji3K0H2ThdouQ3G6IThGeEgmqsF9A1eUiRF5pFlvopo7v"
    "nx+jr7ynu6LX1dHcgrqGRrgkJ3RTwIcwj6GwDQMzioaFd5OU0hpAD8lRMDARfRlC2emnKlN2"
    "dzouom+OwddwLpeKrYSQ+jKDzZE1KLMGTMOag0WSYnG/j7KnoxrlF3th0McnBuahzqSRka1S"
    "V0gR0hIpStrID5S808BadlI9qYtUnAcsMGEF5/+9TsoWLtduA+RBT/7MAqwKtva6kX+7pcz/"
    "BP4AeLD+4/t4r9cAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
libro_verde = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAKnRFWHRDcmVhdGlvbiBUaW1l"
    "AFNhIDkgRmViIDIwMDIgMTY6MDE6NTEgKzAxMDCR21o5AAAAB3RJTUUH1AcHCBsxnHeKKAAA"
    "AAlwSFlzAAAK8AAACvABQqw0mAAAAARnQU1BAACxjwv8YQUAAAKhSURBVHjajZPLTxNRFMa/"
    "maEz2OmTBm14lD5A0QgJylOJqIuakJgY4goXuvIvUBf+BW7cGFfujXsNyEpIBHwEApIAmkop"
    "IlD7gNJpp51pp+MZMhjEiN7kS2Yy5/fdM989l8HRiznwrP+rgMEwWLShFTl0s1Z0nfDYzufk"
    "kiw9UW4jhh9Uo/xp8AJXoWGwTnR2ullLh4cXHC4bD0VWwak2lMQiJkbWXpee4gHhkcMm3MDd"
    "4HzoWNOVcNDn11IWoYlrRX3lDHq8YVyoDyO9mwIasi1bfN6OOXwiRiJVfhnUXrc+9Dc4hHSa"
    "QUHN4pr/BjzOWoiCDYVyHiIvIppbghiobk9CLmERy8Tl9024fLt6ebC3OTQZ+Q6v14q1+Dpi"
    "cgQT8VFMJMcwl5mDoulgLSxj8XHd0q6SxCq+EisbwXKKV0uzbn24raWWWYkVIYlbSJWSUHSN"
    "AuJpGxblig6lXAZr1dlyY7lPXdejFGmMDAoshfh2empjVNCpSMvDxtQQwFCu9M5oVKFgp7KL"
    "aCKD1YUsTuc7rOR8luAAia8yWlHmy4/GA7HwwEDAMj6fAHdcwWZyBzsJyk+qQ2flEi56+tF3"
    "qhdNDY1y6H5IIE4ksVV7YbzB7JdA6nmo2XFn6/02gvxJ3HL1o7umC26/C3anHTabCJfTDdZd"
    "saKH/u0DCgZbZZ5GUVvG41dj0aGhtZuOvvZehHxB2O0OlDgFH4uTmIm/w1RqsrAZyyyYA+gm"
    "CfsGOqZpSFrwTBWL95bURYyujGBWnqlkt6UIoviMFWxTcCUKx5iDb+ZR6r+Pcgg+nMNLak7C"
    "EmGbNHXFvVaTpA3SOilOypgDlTtoYCwLqZnUT6o2AQNMG8Xm2RdJ2v7lOmwAE3Sb3wzA6EA9"
    "6kb+7ZYy/1P4ExagDOhLRsnPAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
libro_azul_key = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAArwAAAK8AFCrDSYAAAAB3RJTUUH3wULFQohnDaVZAAAAp5JREFUOMuNk9tLk3EY"
    "xz+/HfTd4Z05l01FzTmnoQRL7ahWQoGVUQiFEXQRdICgoPAiOkB3/QWdoLwQiqKToFBUF8rS"
    "DgOxBE0b1hpYuaU7vZtr77qxKOn0XD0X3+8HnofvV/D3ET/tmX8JBNzU0K6tIiJWYjDVI1tq"
    "UcJxek/uY9b7EUguBOg44m9GpLYgS3Vkx90gWVw6H56WTrLlQp54X7MjfOQiPYc6IDm+EKIp"
    "LhJ3XYWa41nlBevlRNpSK0Xp23QFm/s09+49pWlNG9d33myh6XwHUALofwH4ZxSht1rJnw6Q"
    "SAs2VptQhQyJYUpLknj6rtFYbQfnur24zxwECgHdDwBv3gwE8mREKESlYYy66TNYyxoh7KWp"
    "9Tjbdh0lGHgL6TmBc8NRKva3A/mAFkCLvjKYMJfvkSrLxZPac6xYZmDs4Sn0ksTEYDeBkT5a"
    "uw8QTppAVTUYytagzPqITkwCio5XZ/vJc/Rm5ddstZXW8eLOCZY6bXT0buDqRAOk0qDMwWwc"
    "knHclRnj0Ei6JgNDQEQAGooOr/XdUPvfD1yixCHR1NPJh1ABRKMssXxhtT3GWpeWVS4jxcX2"
    "WPny5i7gBvBMB6gELngf3i+Ycjuwb75yjEKrn101H6gr1ZCTY0bOycFsMpO7SCZuLDBS1JZF"
    "4LYCqN+/mTjU1bCJ0jbPbvtVS31VNY4KFxbZRCJj5NGkAc+klsejMYV3D4ZREUAukK37EdOp"
    "W+PYGi/Hhe3EyCczPW8FLydVNfLx8ziR56OEB0PEJlJkUhHgPRADMr9GObe+hMXbu0lFIwQf"
    "+4iPJvkaVYDPQADwA1PADBABomJBtPWAE2gApHlDAAgCUSAOJID093KJ3xRMmr9PzBsUYO5v"
    "jfxTS8X/CL8BhlHvmzckpZwAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
libro_azul_key2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAArwAAAK8AFCrDSYAAAAB3RJTUUH3wULFSI0rLbfJQAAAq1JREFUOMuNk1tI02EY"
    "h59vLub0v5k4l1IeEjNLSq12EZhhqCRJBykqKuhw0U0RkWRFUV0GSYEQ2IUKFlZWRqWlJmlh"
    "jpKSYSq6lstm1nCUm3N52NeNsyPVd/Xy8P5e+OD3CP7+xA+z5F/LK1MvqIuO5RU4X+6VI30n"
    "ZX1Vtpvt9Y81huVx9acxBbi9bpH5e+zAwBoO2s5zYrCZs9YvQ893SSnfyhNFWdJlr5RV5fmS"
    "deV1AV5dRJ3LXim7biSaAdQxc0WNFpW+3xiNxtqLX+jAZyE7zYfFXM6q5DiIN+X5xQvwWUhZ"
    "IkKHmnc90CftyQMrgqK+kZT5Rl3EcAv7ou6wdUMOmqlu0KUhVSpeXj9D53g62zblznCCgrDc"
    "KyZ18xOhpre3zWFKzL2/6BrGKIXuOzuIWZqLw1bD5JSaiPjFbIma9Rt/VvdqGYAaa/tFXWtQ"
    "juHQCvHidiHxiQaONmZTZs9i3ngX3WeczPCalZS1p47SWXpY61K9B78QgGJ7ut/9rq2U2IRg"
    "8lsr6fLEwaTEtreMAM+8fI73I0bSFyI7GstL5GDDFcCiArztDyteaRVY/cGM0xMNE2pwfaW6"
    "5hlaBU42FHJwbQjNpyQ3j8zxysEGDRAKqAJF0bKs5BIbd+5WWq6y2OgjIwFWxKkIC1PQhelR"
    "QhXCZ+vwhkTLlMzjFThulQId6ukDPgafFFMbWbAu6q7elJxCwoIk9LpQfDKER/1aWvuDaOoZ"
    "HcNeb8GPAMIBjXqmpkPVfRhWXfYKQ+HrTwq1bwTt/X6/+6OzD/fzHkbMLkatE8gJN/AOGAWk"
    "+Kn34aZYItffZcLjZrjJhrfnK5OeMcAJOIABYAj4DLgBj/jFh1lAIpABBE8HHMAw4AG8gA+Y"
    "Csgl/iBV8PT/xHRgDBj/XyN/1Fj8z+I3WjsmcYcTCMgAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
key = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAArwAAAK8AFCrDSY"
    "AAAAB3RJTUUH3wULFDowKALpUgAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeB"
    "DhcAAAGvSURBVDjLlZMxaFNRFIa/BMHBIY1WDKJDu0TQ5QWEEhwirh0KDu4Whwx2zOIQsoou"
    "DiqIkEF5pEIpkqUivFCeUJQMti/Y9NGpJW0xEUsNNa8Nv8OtLxSteV443Psf+M4595x7YwxZ"
    "LSen7nYt1GdSOS7erMWIsnwbdbwZSeuhdbwZNV8jomRuf84bsL+ixkJelQJSf0U/Wi/llYcE"
    "8coYuOdKPVfVkgGqJaSeq62Pd7X8ZkLxoaX0d6G/Sypl5GSRWL18g9S12+xtLXHqJO5n7+hw"
    "0AZg/PoUvj0vgHPpKThoEwT8PUBjIa/43jsjDk2A5JV7JK3Hxre/CvurdLtwbBwfnqCRdJ7v"
    "zWdk76/DzosTb7b2yWVz83DgcB6Zpv3etTEt30bamP7DvsxZmntgmhpWULdzGhsPSJ4fBWD2"
    "+VsyFiQuZfHqTb62OmGy0bEJbuWXjj+mauko81pWlQLybdRxr6paQv5i8d8zD+FGOoTbzuVw"
    "9tHg5QsD+P3ZaDAQDwJg+ymzr3bIWDCSPM2i843JIpE+TKxSQBnLiEQCnBrceRgNDqdQKQzK"
    "/R8Y4BeDNgjG7ossowAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
db1 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wYSDiEmDuDT+gAAArpJREFUOMtlk01rKmcU"
    "x38zI7GO4GPEwCzUS5lCyCJaA1l1cxFsP0Dox8iHyM2u+yyy7LoNSYULaXDRje5MwMBA4I6a"
    "KKhofJ+RJM7zdNFqaO9/deCc/wuHc+BfnJ2drUsuLy8LtVrteDqdfppOp59qtdrx1dVVYd0/"
    "Pz/nK5ycnHxoNBqfZ7OZWq1WSimlpJQqCAIlpVSr1UrNZjPVaDQ+n56efljzNIByufzj3t7e"
    "n+FwmK2tLQzDQNM0NE1DKQWAlJIgCHh7e+Pl5YWHh4efCoXCTQhge3u7tFwueX19BSAIgg1x"
    "46RpGIax6QshSsA3IQDP88K6riOlBEDX9Q1pDaUUUkqUUhiGged5YYAQwP39PbZtE41Gv3L+"
    "PzRNw/d9XNdlI/D09EQymSQIAuLxOEopdF3fJFi7a5rGZDJhsVjw+Pj4T1qAdDqN4ziUSiUA"
    "MpkMUkoikQiRSAQpJZlMBoBSqYTjOKTT6XeBTqdDNpvFtm0qlQrNZhPHcfB9H9/3cRyHZrNJ"
    "pVLBtm2y2SydTuddwLIsXNel3W5TLBYRQpBMJun3+/T7fZLJJEIIisUi7XYb13WxLOtdYDwe"
    "k0qliEajVKtV4vE4w+GQWCxGLBZjOBwSj8epVqtEo1FSqRTj8XizRN00TQaDAaZpks/nqdfr"
    "CCHwPA8AIQT1ep18Ps/z8/NmFtB1IDyfzxFC0Ov16Ha75HI5PM/DNE1M08TzPHK5HN1ul16v"
    "hxCC+XwOEDaAlWEY3+7u7n4fi8XY2dlhNBqxXC4JhUKb0/V9/z/3cH19/Wur1frdAGi1Wn8E"
    "QRCZTCY/5HI59vf36XQ6WJZFJBJhsVhweHjIYDDg5uaGu7u7X8rl8vHmmSzLotfrAWwfHBz8"
    "fHR09HE0Gn1n23YcwHXdSSKR+HJxcfHX7e3tb8A4kUgwGo34G49MXnyWzkkKAAAAAElFTkSu"
    "QmCC")

#----------------------------------------------------------------------
db2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wYSDiINiXF5eQAAAx5JREFUOMuNk01PHHUA"
    "h5+Z/8vM7rJAKps0tbFaoFlYa4jGiqVpgxejjR5akjYxMR707sWLF/0GajHpqRdjYlKjB8RD"
    "ExN8T20i0mrZhYWybLd2gZllgZ2dfZkXD1QOnnw+wJPnd/gZPGLuhx+ZPHcWgL+rD4er1Y2c"
    "5zUzGEacTFhOIpH4czQ7ssp/MAC+uP6l8XRu1CosFa9Iqd6JohChFFoplJRIpVBSYZgxzUbz"
    "0+mrV9+9NHUxfOPypX3BL7/+LO4WVptKSZ1IJknYCWzbwrZttFJIaWIYAiFMlFLUXHfn7JmJ"
    "fgATYLm4eiqKYy2VRkmJVhLL0vsSy0JrC9vSWMpCCMHAwEDfR1emTxwI8kuF6FBfmp5UAikk"
    "Sim0tpCmQEmBVhqlNEoLbMvi9/l51kulCEACSKEJw4BuM+T0+Di+7+O3fKQwEUqgpEG6J0Wr"
    "02Ixf5dNp4pQgoOCZrOB47h0u12SqRTHnzyGpRV3Cgt8feNzCvcXCfHY2C2w3d6iHXlEdDko"
    "sG2bmuvi+T6ddhtfmrQCj47YJu5ZRGf+ohqMknwsw/G0g9sp8dVnlXDs9OF9gTAF2WwWz/eZ"
    "+36OMG5Ra1fYje4wNnGTntSb9Fk5dtsVMqkxRk/6XP6wOPve69WcAHhh/MWjyWTybWVZnH/1"
    "FU499zx2OkU5+IAe+wS99lPcrn5LN94gCCMs1YvTXcocOiJXHk2wcF2X3jDAb7dgL2DDKbFW"
    "a6BlnZn5azw7fAwtTcq1G1S3JOmUjz7snRcA2/X60NTFqbdiYra2Nlkp51mq3OLWw9+QRshE"
    "NsfKA4fKjsPR/iGSVofyZpnSvUZJAhTy+dhrehhCMDn5Ev3pNH8Uhvnm+icU7tfxgwVWlnyC"
    "OCR4xkdaAbXtNpjxbQEQhWG5vrNjj2RHzgwODhF0O9T2NlmvFKlF6zT9kHv5AMeNSKZCgiii"
    "4XWYfb/1mvj3VaW1te9mZ2au1erbjmHQLS6vRuz1dlfWF8LeI2378SdMBockUsfs7XVY/ik4"
    "5y6zbPA/yOSMl09e4ELcidN+01i8OW1+DGED4B9MUl4ZkR9Q5AAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
db3 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wYSDiMM5214rgAAAxRJREFUOMuN089rHGUc"
    "x/H3zPM8M7O72SQmq4JUW2Iqm6beRFoN1aCCET1oA63tRRTBo/+AV69iKxQEry3oRRovghqj"
    "VSo0CUFDdrOJ+dEku7o7+6O7O7MzszOPh8QcPPn+A158voevwVHzCz8x/cIFAA4q5dOVyl+T"
    "3a73MIah0ym7lkqlfj+Tn9jkPxkAt778yjg7ecYuFEvXpFTvJ0mMUApLKZSUSKVQUmGYGq/j"
    "fXb9xo0PL81ejK9evnQI/PLrHbFa2PSUklYqnSblpHAcG8dxsJRCShPDEAhhopSi7rqtC1PP"
    "DwOYAOulzWcTrS2pLJSUWEpi29YhYttYlo1jW9jKRghBLpcb+uTa9aeOgbViIRkZyjKQSSGF"
    "RCmFZdlIUxyBFkpZKEvg2DaLS0vsbG8lABJACos47hN5Mc+dO4fv+/g9HykkppIIqcgOZAjC"
    "kNVCkUqtiqksjhd4XodazSWKItKZDGOnTmJZNsuFIje//YGN/X0asWa51qQehPS0idYGxwsc"
    "x6HuunR9nzDo4UuB1+/TFhZrKsPXbcXYbovHnAzlgcfpChfz7q04+/Qzh4AwBfl8nq7vM//j"
    "AqHWVALNstdnbnSMmUyGE9Jkr9Zm6mSOBS/P4ivvzbU/evesBAiCkEaziZNOMzMzw9BglpXt"
    "HT6+eYdcNsBIEuKwT90LGBCCYccCZ2hy8K0P3j46wcZ1XQbjPr0gQLehVK7iFXdRQY/C33Ua"
    "j+Zom4KfS/us3lsl6hsEzuhrAqDRbI7PXpx9J0FTrVYp7hxwb2uPu98vEdVrtO7v4jYCWuUa"
    "2xt77C8vkjhZws3SpglQWFvTXa+LKQTT0y9y5Y1XufzSeQhDdCdEZ0YJum1ai78RjTyEcSpP"
    "sLcPWq8IgCSOd5utljORn5gaf3KcKIqotjqUygfslB+QPGgTu1X09jpxZoSk7pJ0OyTzn78u"
    "/v2q7a2t7765ffuLerNRMw0j2lhfT4ZSRMur63E0+IiDY2M+cZok8NHdNvrPxfM0D7YM/k/D"
    "J15mcvpN0IN0Wn+wMvcp0AP4B/W/ZWqwsB+2AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
pazul = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAACbUlE"
    "QVQokV2SPUxTYRiFz/t99wpoQSzgpRiuDbZGQ8IgcSFAiAyYxsEYcTDoAELLoAMTg4tiCBNu"
    "pok/kz+JqwkJEk0jhpGIkcTEQkqLbWmlaCG0vdzvvg5AFJ7hTM9ZTg74IH19N71ej6aRrgu/"
    "vzEYHDwkaNgnFBqamnrd3jpx63qP260BnMuVotGMaYpAYCAcfrqrETMD6Om5ZJrrzU3jyURl"
    "bOk44AAAHO+ZpYbGb4vL4/F42/T0p71CKDSkVLTF/3j2gyu3LooFoRQBkFKVV2y7a9Y6uiNf"
    "f4xJORAOPyNmNs2akeH5uUjZWtrJ/1GWxRXlGoBC0Saya2pLRn2qrWtm8slEPMEynU4aVXfJ"
    "aVqOimIBhW2HIIgkM5gJLDQNSmkuV6Ha1TITeSnz+Wxn27Xo97qNHFkWbJtBQhAB5DAACCEA"
    "UrZ+1r/67v0rLRb76XbbwKZSVTuW0HWNGcwAoEkiEmBWSsIR7qojsVhGAAAU4ACs6wAYYBxk"
    "cxNgAaUBEF7vqVxuC9iR0i5ZisgBMRETMfbTcRQckVsn7+k62dt7I5UomWYxm6klyEJBaJIA"
    "EEEQC+GULNtjWOd9K7HV7LmWo7uzipHh+3ORrrW0xyod2cnrRRAAgEnY7uodo/Z324Uvk2/u"
    "xVMlASAQ6F9cftTR/dGoTx1zbZWfKFbCqoQlpWXUFY3ajY6LC4srDwM9V/6/RqdpzjY3jSYT"
    "3tiSDwBYwta9jcmGuuxibCz+yzMdmf9XABAK3Zmaet7eOurzwV0tYZflMnp0WX1eeBC4fDX8"
    "4u3eZIfeGwz2+/2GrkHX4PedDA7ePiT8BXmVVTI0+IzEAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
projo = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAACU0lE"
    "QVQokV2STUhUcRTFz/2/93yjaeDn1JQz4ahgiIYhFUhCi8TJjeC0DPxiCHITLVoEtQg3RosW"
    "NZC0K2gh7rKpQDGQSAyiSAkGnTTHQR3Rcd447+N/W8xMlmd1L/zOvYfLBf8jmTZu9gXPez0e"
    "TT1VpF3w14ZCw/y/iJkBABgZGpx/O3Er4G9vqfCcLAL4t5Gd/h598mqt81p/OPw8h+UNwSud"
    "jdXJu71t5sSKTGQgJQRTKQn3Adw79zc2f8YvRiKzecPI0GDN9tLtvquZl3NOdJNtB4YDAC6i"
    "Mqn6M0qTeW89brv6w+FxkmnjUqP3/dNH5vgb60fU2TsAs0IEQDI7xFq51Fqzomm/9cXWr1VW"
    "thPxnmZ340LC/hbFnkGSCSAiACAQE1nEKSGOo7Xc9Xh6UTFSW3eCza5PcbmxA9sBA38NuRqA"
    "QxCitB4PPyyqsdh61XxMOgYsSzJEDgUAJkJ+kcMyqVZkaGVlVQAgHVAZBFFA88MLXdYmgMAK"
    "AOHzeZJmRhyTEJBH0MLlpWRA7KbpjK9a6Q1e361415KBs0VkkpR0GAoAYAF6iaKeVhacrN3c"
    "Qczs9Yqv/SesmRK5rMEi2OQUkoFY1UlUCu2cPjq1OpZICACBwMCD5U09kBJ+EzpDZ4VZATsE"
    "1SVEpdDbXJNLyVR3x+FrdHVd9no/jtVVWjNlbEPGdDBRmVCqhFKrTS7tvNbLIzNfgMJhIpFZ"
    "RRlsebY9X5xK+7J6z77efWCcNeeKU6NTa5+b2nM0ABz53lBooKHBranQVDTU14SGbxwB/gAs"
    "SkLRMgIh7QAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
pverde = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAACOElE"
    "QVQokWWSzUtUYRTGn/PeD6/W1KBm04xeh2zUJIIKTYmKFBoRW7WRShcDOvMHtKx/oFXuBgyC"
    "NhWh0CaaXRi2jBYjlpiOcx2drNHmU2f0vqfFVcTp4SzO4vecD3jAx/Xg0Yj//DmtRuiGEuho"
    "CYfHqwBiZgAAIpGJDx9f3x9rv9rd6PXqAG/92fkytzz9Kjk0GIpGpxzswHB38I63JTMa6Xn7"
    "eenX35KUNgBdZY97f3TAmnpeWEv2xWKzB4ZIZGLX/u65bi6sWZlcvrSzLxkABOFkrfTUVzqb"
    "y6k5S1NC0egLYmbT3/DwycjC2oq1ub4vJUsmQQBYMhi6Ltu8lU5f8eXTjaTFSjq9fuWGJ1Up"
    "rKZTe9JmySAQEQ4lQfmS0FXqvbQ3/WZJyeV+mzfd26VyJpflQ+jIQCACM9x1OOEyYu/mRSKR"
    "OuWys8WMBMAgokOaieC0kmkrp7hdWiKxqQJQBAPszHNQHBdLAAISAITf78vni4qwCWDm/2nn"
    "e2KRz8Lfekb09weTq5a3saAqtnNutSQMTfhcWEna/bcHiJlNUww/9n/7aexWhM0EPtpCDEXA"
    "UKmnWZuZjCc3ygLA0FAoES92t5cMXeqKBDExnNIVMlTqNfXF+exQcPgoGsHgLaX1R9vlmuW0"
    "sZ1XbRuAUIga6qitXl2MZ23rdOzTVwDCWR2LzZri3vtnVm250OUr9F0s9XWUu5r2anaKM5Nx"
    "U7vm0ABQld5wOBQInNVUaCoCF5rC42NVwD/FRD0shPDovQAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
refrescar = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wYSDiUkhIJ30gAAAshJREFUOMuFk1toHHUU"
    "h7/5z+zMZHeTGbe7uSxpk6bV9CIWBdsSqq1SyEMpLUIpCL5YBOm7+CDoi5cHBcE335QUbF/0"
    "QRBaUPC2WAmUoLXxUuKaq9lNd7PXmdn/zPEhqKmF+j0efr8PzoFjiIiwjbDXpdmtUGuVqTZ+"
    "x3EyZJ0CuewYA31D2Clnexxju2D+j++4ufYRETdQVgOlDARBEoO410/WPMre/FkOjE8Rxwmm"
    "qbYEOtaUbs1wRy4TRhtorRHR9HoagFTKwjAsTMvEsQZR7VM0ozmmH30FC+D26vcstT8kSepE"
    "vYQ4smlujtHv7gOgFszT7y1j2hHaXiOduYSdDmh0/sRqdjf44qdX8fwaOhaqGyZH97zMkyfP"
    "3bVr6ebHlH59i0I+pNMNaActZAisn5e/YsBfRqkUrU7AsYfeZurgGf6LnxnHcRwMo0cUJUgi"
    "iAhqNHeI2dkBvi4pht0LHNl/6p7y4vovzK28SbEYEScxAH9f3hrOTfDuxevcD6U0KhmhteGj"
    "BATBTjRZN4+xVPlNltYXUMrcMifgZXfw4OjBf2b3w3r/2jmeeHwIURFKJViWxQ/lNTa7r3N4"
    "8sz/CzqdkIWFCsoSQAhCTT59lkMT0/eEV++UufTtaTrRCkEUcv7IFRSiiCMTHYICVqvC1P7n"
    "cVLuXeXlapkr37zIzqLJ3pFxfLdIwZtABVEbSVIYhoHWwsOTDp/NvcDV2Rl0HKPjmKuzM3x6"
    "4wLDxXVam8LKWpPBzDSD3m6Mi+/tkZ07ChiWg9tXwxuw8Xyh0Wlze7ECGOweLdDvZqjXe7Sb"
    "CW7qMc4ffwc/k8f44NpLku3Lc+KR57j85WtU6iXSmS457wHSfTYGQjcIqTU2aTRdhv1jPPv0"
    "G3iZ/NY3hr2umMrEVCkiHVCtL/Jj+XOu3/qE1fo8ChjJTXJ43zMc2PUUBX8M2/r3Pn8BRkYy"
    "KRCV5sYAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
process = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAO1SURBVHjaYmBAA8LC5gyMjOwM"
    "urpB011dWz7z8ytHCgoquYaGdt7Iypp4gJGRVQRZPUAAMaIbIChozCAqqjRVRcU8i5+fk4GF"
    "hY2Bh4cbKMbLICUlynDs2M5jixY1BTMw/H0BUg8QQHAD2NmFdIyMIhd/+/aXSUhIRk9JSYyB"
    "n58HrJmTk4OBlZWZQVlZjOHvX1aG0tLyfffvb/IGavsJEEDMMAO0tSN38/DI6UtKioqHhdkx"
    "uLgYMKiqSjFwcXECNf0D0uwMTEyMQO+BLOMUvnHjzNGfP7/cBwggZoTTdTKVlBTF09LcgeHA"
    "x3DixD2GI0duAulLDJKSAgwyMiIMzMxMDEJCXAzOzmbsLCyyVidP7j8IEEBgAxQUXCepq1t6"
    "RkTYM3NzczHs2XMd6NfTvy9dOnH3yJGpJZ8//2GxsnJU4+dnB3qHhQFE///PI3zkyNGPAAHE"
    "oq8fMkNNzSldVlaQQU5OhGHv3hsM589f+X3s2NyeL18ebQCaf+nbt896rKysDAICkLB49uwD"
    "0DX/GCwsIkoAAohFTc05XVSUh0FeXpzh/fvvDJcv32I4fHjGhG/fHq8CaRYSUjSPjEwKkpDg"
    "BGpmYnj8+D3D9etPgYa8Z/jw4f13gABi+vjx/mF2dnZwQH38+A1oyAeGb9+enARqviAgIGdS"
    "UzNjh7e3rbyAABvDnz9/Ga5de8pw4cI9hpMnz3w5dWpeE0AAMR06tKCegYEJHNq/fv0FBhLv"
    "D3Z2YHIyj+iqqpq8xdXVhI+R8TcwOtmB6YCf4dOnbwy3bl3/ePv2mtYvX55uBQggFmVlbXUB"
    "AS5g1LAAA4iVwd/fhkVRsa/F2dleVEyMg4Gbm5GBg4Mb6H9QdP4HqmNkuHNn69z37+9tArry"
    "GUAAMYeH53Vqa+sqiovzgAOIn5+LSU9PnVtEhA2YChkZfvz4DYxWbqDz/zEcPHiH4d8/FoY3"
    "b34IPXhwci7QgLcAAcR86tTuzdzc4uaqqnoKIA3i4vxAlzABNTMx3L79CujXe8BYeczw7t0v"
    "hpcvvwDZ9xiuXr30/c2by6BAfg8QQNCkzCRqaBi3QU1N3yIlxf2fsbEqy9WrjxmOH7/LcPHi"
    "PaBBN7/z87O8ePfuHdP37z8ZHzzYAYyl11uAGh8ABBA8LwBzmTIHh0SArKwkR3FxX4ugIB8w"
    "MV0HhfbXO3fWNr9+fW83UNkfaP75BsSgzPQZIIDQMyMbEHOJiekVBAX1f3Z0rH3HxSVeChTT"
    "BKV2qDwIs8A0AAQYAAWOPI69PFvBAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
smiles = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAA6cAAAOnAEHlFPdAAAAB3RJTUUH4AwNFQINu2D7WgAAAoNJREFUOMttk99L01EY"
    "xj/f7/Zd06WQMDN0c2YjFoJEUCCJpKCi0U03UaMLf7Sx2xAvu+mi9Qd4s7zpD/BGhCYkYVcS"
    "iJExh5nmD5CgQHTLfb9bTxebNsoD78U573nO+57neR8k8W9Eow8VCl2S223IskyFwwHFYuM6"
    "665J1YrHnygYPK+Ojq/MznaRzz8il3vAzEwnbW1pgkFT8fi4qjGGVN4PDPQqGPzB1NQ9LMsG"
    "csARUAIKwAaOkyGRsNne7iKdXjSAcgflypBKvcCyIoCvAjwpdgzksSyDVOocweB74vGxclIS"
    "gUCDbDsjaUvSvCYmJlRORSVFBcjv90uqlVQj20aBFiQJIxYbV1tbkcnJZ4AL+IxhDFYejwIH"
    "RCLrrK2tIdWCSlA0SL4ssbkdxVxYeMPwcDOwB2wAK1UUFYA9dnZ2qs5+Q6GW4b46FhbmMCzL"
    "VC73FMuqA44ZHd1neto+JQ52KoRWwKUSHDTiHLvwtW6fyGhXGD9ketoBDoBPQLYKLFCRyy1e"
    "cGrA8QJghkLNZLO7wHcgSyTyAViqVNZfMA6UTDb3DyFfR3bNINTqx93bO8Dc3Gs6OjyAyGTA"
    "5xO5XNWfKULJ4Ma1OrTVDPl65uZ/0tvTdyKjIduuqchUlkperzwej9xul3xetzrbG6S9q1Km"
    "W/byHQWaPDod5aGhERKJ43KbJ/HLoeA4OC6DW5FGVt4G4NAPRQ+J51mGBu5yOkiS6O/v1tgY"
    "su0qr5RM6eiCtBuRvtyU/fG2xu43qb/nuv4zUzq9aLhco7S3QzIJq6vgFFw4BZPV9SOSr77R"
    "PriEq76b9Ltl43QszrJoLDaicPiiLDey3Ch8pVGx8cdn2vkPPDCIKs37Cy8AAAAASUVORK5C"
    "YII=")

#----------------------------------------------------------------------
miscellaneous = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACk0lEQVR4nKWSWUiUYRSGn2/m"
    "G20axyWzbcoM0xaywougIEupixbIkOiicGunm+yqboQWpCiyhRajTJC86qKFaDMCKyrCQq3U"
    "tG0mG2uadKb5/XNm/v/rQgILo6Jz+Z5zngPveaVSiv8p+aeBYeu8c4TxOVevydr/TwDrRmPC"
    "lpKo+9iRsQgxlsQ1T6b3ns8u+itAckF1ad7+0rO9VisNvgFtRUV2YfL6rkn+M66cPwJspk3W"
    "x0J8KwSjgIKMJMjZ55ovYmfZVX+TPjQgXyzUMtPOyciu3QQh6ILsLrCng80Kl7qBupfzgZs/"
    "AczFIl6sXvlBVN5yOAxFxanrZ4sCA5ejI+BhN5gKVBSqCg7eiDmZWhbe4j4MIMMbki7ElB8s"
    "IBqFzscQNSjMTRCPaqs5sawU0wGGBlhh4uW7+OYEKCtcWxl3OnVGaKN7vTRkjJ03V+HFa5Bx"
    "YCgI9HB8zBi+VLTozTsr7Un1bczeXIZ9m4MHXWAKk8kLXOtksbNNarqJ3ReAUSnQ1A7xSbCk"
    "BEzFlNqjja3x7eN7tt5J84YzaWv1IG2SuVkzyUvI4UVPy2gZ+mYy0q8NOJI5FZQDWh6D/x26"
    "boI13I/PRhtvmJeRTcgIE+rtp8pbAxEDufX2l/Iryc6llkgEdMDfBUqBEGh9huVth+cpidYp"
    "CAvvNT+ePi9KmSDAZhjIqz7VmBojMp6vGtfhDIfg41c+RSwsagjWtRhqkyppDzm2j/6mTxPF"
    "ptOC+ioRQmBtDHoityM1EsAdVp1xQqQ0rkzz7biv3buomauUUt0/fq0d+lgSm+94Fbs8fc9w"
    "j1fvO+AriOjqGicHBSmk1GchhFRKGUOls/+itlcIcRl4ppQyh0zi75YH9Zt/1b4DIgMimftg"
    "s4wAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
sql = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wUfFwwRMEoW6AAAABl0RVh0Q29tbWVudABD"
    "cmVhdGVkIHdpdGggR0lNUFeBDhcAAAKJSURBVDjLjZLPSxRhGMc/Mzvu7oy7Myq2YGALRT8W"
    "AqEfdkorCSRbq4v4F2TkIaSkTuJp65AUeEjBU91cOxnUIfqBoRFF4SkMoiKK1mbXdXZndnNm"
    "3g66i9YGPfDwPjwv7/f5fr/vI7ERfX19SSFEC/8RkiR9n56engVQKs1SqdQyNTU1WSwWcRwH"
    "1/VYXi7gOD7hsEo0GkXXdQxDZ2Cgb7DyTmlvP/ysrq6u0zR/cu7c2X9Oje/YxdDlUbR6deuF"
    "EdHETDotfN8Xm+uZdFoYEa3aNyKaePX6g/j0ZUUkk8mLVQZW2WP33n0cO9GFVfY41dODElIp"
    "5HNYZY9SqYRV9gAQeAi8LQQUPRbn2uh1xm6OcfJMP7Zto8fif50Ai2/nWFpaehQIBF5XAORY"
    "PMHk7Ru8//iVWDzBwyfzLC485uGTeWLxBLZts7jwmFg8wZGjXQwOXe32PO9QlUHT9p3P+4fH"
    "OwGaW/dw5/4cd+7PcS91gebWPfQPjwNwoP0IVnEVVQttlfBy5tYxgN7e3vMTExOTmUyGd+8/"
    "c3f2BWc69hPVZNT6MI1NDbU9qPVlrdsitDSq/MiuYJUdhOQj8PA3siaALMtvUqnUg7a2ttO+"
    "72PbNqZp4rou4XCYbCTCT8Ng9g8TqwBra2sHR0ZGTm/exEx2hbxTRAnJ1EdUdD1KR09X95WB"
    "S7PAqy0AhUJBuK5LPp+vTv6Ry5H/VSSkBWkQOrIi0LQQlmVVdciVIpfLKbWXWKx7IPkI1jOb"
    "zQY2S1CBqGmamqIoGIZBMBjEdT0CIRWttIockqiPqGiaSkCRMU1TBWKAJQFNwHZVVY8LIZp9"
    "38f3fQAJkGRZrpiMLMsCQAix7DjOU+Dbb4FAMFi7QM27AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
cuadro = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wYHFSo7+aaN1AAAADNJREFUOMtj/P//PwMl"
    "gImBQkCxASzInJ07dxKlyd3dfRB5YdSAYWEA44Blpt+/f1PHBQDWcw8IAHFJDwAAAABJRU5E"
    "rkJggg==")

#----------------------------------------------------------------------
flecha = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wYHFSQ1gJ2NXQAAAHFJREFUOMu1klEKwDAI"
    "Q+Ps/e/blpB9rQxZaaUsv6J5Rk0STnThUMsBZqbW2ry+WsHMBACS7GiFGckgeJxWiiTpECNJ"
    "miCS/H/GL9VaRw4l2xxDLLNC/IPonCZ4G5CEu+9nEOncHb33vVdOXYEkSKYG3F9URZ2yU5P2"
    "AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
flechaarriba = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAADpJ"
    "REFUOI1jZGSgDDBRqH8oGPCfgeE/2QbANOMzBKcB6JpwGUKbMMBlGzZxDAMIBRq6PONoShwE"
    "BgAAXjsSD+h9gaIAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
flechaabajo = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAEVJ"
    "REFUOI1jZGSgDDBRqH/UAAYGBhZ0gf8MDP8JaWJkYIBHHoYLkCUJacZqAD5DsInTLhDRbcPl"
    "KrwugGnCFy6Mo3mBAQBXfQIzloIPQQAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
info = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAu9J"
    "REFUOI1dk81rXGUUxn/ve29mMjNmxsR0oqTYjqVSDKkoteDCiCBINS6TTdcKGrvwD1AG/4fU"
    "EpdmYXWl1IA7W0GkUKi1JSliUmvTODOhna/cO/f9Oi6SjtUDBw7P+eA5z+Eo/mdzn12ejSK9"
    "pJF3xFMFUBFN8VwKwS//WH/j5uP16lFw5txaPn0qdyGfixdP16qjR6tl/WQhD0A7ydhq9cLV"
    "zZ1BZsNXuzz44FZ90QwHnDm3lu9X1JXnpiqzr52YLnSTQDvxZEY4fbzM+FjM9c0u5aLmyvp2"
    "utVs33gQ9+du1RdNDNAtuQtHJiqzLx09VPjtrw7GClprNIpTx8cQgW9+vkduRPHyscmCdeZk"
    "aLpl4D316sdfz44U4l/efuVEcbORYJyglUIdeLkQY1wgyRxBhHysqE0VWLu6kWbGn9JeuaVa"
    "dTzf6KT00gzrHcY7rHMYZ6kUI4w9wLyjm2Y0OgNqT4/nCGZJizPz5bF81OwkWO+xbr85joX3"
    "36zx6cILPD9dGuLWe5qdhHJxNPLOz8femUmlFP2BBUArRRxp3nrxMF4EgDvNHtY7RIQggvUw"
    "ORYTnKlq5wxpZjHODemnxrL60x8ohG5qubvbw7h/17DOkWQW5zJiCb7V7u8dViisC0PxAGrV"
    "J7i93SFz++xEBBFhJNK0+32CuKYWm13abe16rQVzwMA4R6xheqLIxv2HB4K6YV5HQqvV8sFm"
    "32kfkuXm33cz7zIkHIjoHUeqJZRSHCqPcnbu2JC6BI+3Ga2de5kdmPN6/cv6TWfTi/fv3E6i"
    "kOFNihkkmGxAo51wY6vBFz9cxwwSvEmJQsb25kbijVn9/eIn6wpgZqGeM8FczhULJ0uTzxQF"
    "TQgQ2L+CRqE1KPHs7e4kWZb8Whl/8Pq1lRU7fKaZhXouMb1lpTg7Uqrk4tFSpKMYgOAdbrDn"
    "7V43E2R1otr76NrKiv3PNz6yZ99dmlFEHypkXkSmAJRSDUG+JYTP//z+/Prj9f8AN3XVZUXk"
    "tl8AAAAASUVORK5CYII=")

#----------------------------------------------------------------------
python = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABxUlEQVR42mNkoBAw4pIQNYgW"
    "4hBRN2BkZGL++eHRlZenZz0n2gCDvEvl7AJyESAmVOjf35+fZ5/plM0gygDzug+Xvr28ks4l"
    "rnMMWfz22iSBd1fXfSTGgKlAigfKBbmEDcRgO5cleHjLsg9YDdDPPV/OIajYAmQy4/LqRLPK"
    "FQZCV8K+fPs7R8TlWDpcQkDNg1M9YsUbIJMLd3j//zrfOnerEu/DMBCnbsYDta5Fj++ADZCw"
    "yDaUd2s9h6T4Dwvjn1tMjP9/Adn/mRn//fKV3XE8S31eKiMjAzdIxYItL8Iy2m6vhhhgnmUo"
    "794GNeD/9zyNWTN85XbYMzP8Y2Vk/P+PkeE/kGZQR/begs1AA9qhBgiounOqR658DWRyczF/"
    "Pb7VJVIOaLs0Ax7/1Ey7r9az5MkdeCDqZZ8u5RRWbeFl+Xx8s3OUNtBGEajUX3TNHz7/mSPh"
    "fjwTZzR+P2r7GsmAJUD8E8RomPUgr2PB428E08GPY7YvgZQYjH/5ztdQHWWukti6G+5r9r4h"
    "nJCurDQpU5HlbAIy2aFCd95/+r1N0uNEPtYEgg2EOosIaihy6TMzMTI/ePbj6oItL19gU4fT"
    "AGIBAGsqpBETNfyXAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
flechaup = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wkQDjkOkRe8AwAAAHtJREFUOMvFk0sOgCAM"
    "BVsId+FA7D0bew/kWUpIXUn8PIhaE7siad4wbYBVlSzltkMpxQYIIVCttTVEhGLKGlNWEekC"
    "uDdCTPnQWOaJhwbnmxEQmVwMUHhk4p6EkUkzuBNGJnCJPRhapCNj2QH7x/OPgffeBODPfuPb"
    "WgHUP0ZODatNPQAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
flechadown = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wkQDjkmpKIU+QAAAHpJREFUOMtj/P//PwMl"
    "gImBQsCCTVAjZCFWZ91YE89IVRf8/fuXci9QZAAzM/MAu4CBgYGBEZYOcIU8LgCLEbgLLi2L"
    "ZCRVM4oLCKUBXGkBIwzwuQSbHCOuvIDuEmypEG8sINuGzP779y9xLsAHfv/+zcDKykq+AcgA"
    "APjrNgADJ0mBAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
csv = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB6ElEQVR4XpWTT4gSYRjGnxlm"
    "JDoIbbmHqK4dotNEoGTRQguyTSR5iGgVgzKV6lBsSau7lwqkixFKSImStzoUXuxehzp22kuE"
    "XvzPHqKacdy3eT9wGFpytx88zOX5Xt7n+b6RiAhMrVYrAkhiNqVoNJqCC2dApVKhWCyGWVSr"
    "VTEkHo87Q+SpwbIsMP1+H71eT6jb7aLT6Qgxuq6zL1kul4vbBozHYzCSJLkFWZbFlzFNE+Fw"
    "mL3Joo3wp98tEXbBs/Pv0W63oaoqPB4P6vW6iIPEmxDtBHsmk8k25fN5ki3DQq7wBFcfX8NC"
    "dgFTlh5dgP/BKVy8r4M9g8GA+5l25ETC8suzxDxvFkh/ukjBuwEKZc7RyRWNTq8HiGGPfUjI"
    "LpYlNshms6QYP8dg0ou3Ie3ZwuePX/C91YLPtx+NtSZM/AB7uEgXzgaK+cvClManDzhx3A9z"
    "r4r25jfceJ3AYfUg2MO3QURwYxgGEFrXiDmTCZK2qlFgzU+rbx/S8qsrpN3SiGHPaDSi4XAo"
    "ZPchIqRSKZI5wvV7CeyT5jDvnYN3y4uNrxvwSfM4cuAQLucuORFccjZQzN8WyoUXmEXwzrG/"
    "O3Aen8JX5L95FDvwzxK5GKFIJEIMZ9uNGD6juH6mkv3Ok/g/Sn8AXxB6+TzMMGIAAAAASUVO"
    "RK5CYII=")

#----------------------------------------------------------------------
refresh = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACbUlEQVQ4jYWTwWsTQRTGv7c7"
    "uzvOxt2WLU1CRGPESg5eBC96UETBg6ciih4VPApee2k9CkLBP0IQjEfvhfZUKBYK6UUbWiGh"
    "SZoOySYZN5nxkKSkWvSDxzAzb973ZvgNYSQqFourANqVSmXF9/0LQojbjLGLAIZJkvyI43hN"
    "StkcDocGUyIACIIglc/n9wFwAJsAbgGwcFpKa12q1+vLh4eHe8YYAwA2AGSz2Wee5z0lIoeI"
    "LhGRRSNNRgBgRHQ9lUq9DIKg2m63t7XWsBljlMvlVokoP86cBMYmAGDGAQCO4ziPwjDUUsp1"
    "mp+fv5bJZHYA2BOr0VkDAGo4HJaklKVut7uVJMmx4zizQoibYRg+T5LkK/N9f3HiOOUCAFu1"
    "Wu1Jo9HY01pPr8ujo6NKtVr9HEXRVdvzvFgIcZmIzgHwp4o5rVbrfa/X6+EMGWMQx3Fzkkye"
    "5xHnfIZzXvQ8r+i67pV6vf5BSlk9q8BE9K9NAAjDMJtOp18rpb4rpcpKqXK/3z9WShmttWH/"
    "KwCgzzl/wTmfG881gJoxZqfRaCxZmUxmwXGcMzuxLIs457PGmAMAYyTIBpAjogdCiIcslUrd"
    "jaLoXbvd/hjH8eZgMGgxxmaEEDeCIFi0bfsxAO+PKxsAptPpfCHGGBUKhSXO+TJO43sC1BiP"
    "ky7NSGu7u7v3bK01pJTrQogD13XvA3ABTBA+4XiKSozd3zabzW82AGit0Wq1trXWn4QQc5Zl"
    "LWD0T6YR1saYDSJKA4hrtdorpdSvvx7PsiwKgiDyff+O67oFAPZgMNjvdrsbnU7nZz6fX7Ft"
    "+3y5XH5jjDG/AVKlCwpog1FdAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
asigna = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAVdJ"
    "REFUOI2Vk71OAkEUhc9d7iIxi7G2NPENCNpaGE18BBs7Ar6Cpa/AEh7AzsbCwt7En9hQWFnZ"
    "QC1MNvO3OxYryMCOCVPd3Dn5cu6dM4SK0xsczVxRJMs9iiKRdl+aq1quAriiSK4vOl7v5naY"
    "VGkrAQDgkGMm3wEAzUYrJAsDjFXQxpQ1q80B1koYaxd1ENBLD2fOOW++ehxbbSTPHWiWqMex"
    "7fbbbllHRIKdc0nn/NSjOudYyPHCgZBjXJ4cMxF5uuHDY8IAoIzENPsM2tRmAmDi9Xa2D8oR"
    "SoGEtiYIqIZKH9Dgvb8R4GDsFMp8AwC24l3E3ASB1gFEJO6eRt4SuVazZ619nruKmXH//GFt"
    "nnuvRkSC097rWjy7/bbTWsGYcok6UrB5zoOrN1rVBnMgdbYIUkRZcBdhgJHQv88I+idIoQul"
    "MgC1pXoTAJEYffnfGUSiSvoDO9+hQtkzcqAAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
marca = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAnNJ"
    "REFUOI2VkUtIVGEcxc937/X6uE1TOumY2qBRpEJKpqW4SBRyE1GQ0D4qx4mQoJXQJtwFFY6P"
    "oJXQopEWLUQIKkLw/ciSbMaSGoccnYdOd+7MvfPd72sRSYipnfX//Dj/cwj+Q+19ZwcoRxMH"
    "vx/MVh97WuYNsldzW1d1o81qe9nScD7r3dyktuD/sqEzXifuyc1B6mYdgxfrG/Jz9jOUOUrT"
    "1rV4WjC86hX24m/tqblqP5hbWGizImWGEYv/xMcln0k4ebEr4MrzclkWxQdNp08pOg1AlvLw"
    "enYiwU3e6XaNh6XdALkhi6u4qMByQBFgUB3RWAyfl78ldDH1EAB2THC9r8oqCbhXW3pMUZMB"
    "EFjxamZao4zfeXJjSgMACQCc7nP75LTkMOOwGYxe7m2dHAcAmUsdx4sKZFnSQSnDSjiElUgo"
    "uJZzpB8YxSZAFJPPSvLzTjjyctLfzHx66+qtvUU5hgiB82RxQYaaCCJdOoThD3OqkYLL0+Ix"
    "/6QUbnbVXLJkZTRUHj2cblUYmqvLMpUM+ZEINlJeZJcYYqBMgC/wg6vJ+EKfa2zw7zclETys"
    "JXQhtB6FJYuAEAONFQ5lwR/KLLFbBC0RhSRaMeHzJ1KUObf2RH53UN0sCqKnssSm2LMzCWUa"
    "0kQFJtNBIOBrMEm9y9GhrtbRC1sBAgB0t00MMZNVzSytBea/h3TTBNRkBAlDhWak4PNHU4yR"
    "9u2W2pzR7Rr3JiShwr+qvZ9ejMQNg4NSwLu8oXOB93e3jSzuCACAp9dGIrpA69fj5sDUoqqu"
    "bWhYieiUGEbHdubNDraT033mNgTeyTm52+Mcc//r7hf2EB5b1WSeVwAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
marcaa = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4AodFQILjVr8UAAAAjNJREFUOMuVkk1IFHEY"
    "xn/zsbPrrOv6kehqtYgi4kGJQMXAkIK8VNSpoFPHWrawa9DNU4mFp27lraRDB7HCWxiJCEaE"
    "bSpRfq3rmCvNjrOz//90SCukUp/z+/x43vd5NQ6iQO8wsv0hdBQ0zk36jAll32YtecqsCD0v"
    "775kutOvcplPy1kEndp+vD08UWbVhZGartMxUVJCqL41EMwtB+zMRkrfD2CU8cuRqshhUR3H"
    "sy38vGD144JAk8/UPZPTZ6BxL3r8ZNi1LYyiUvJTLx0o9CEGrT0BQltKRI9URbySKL7rQWYJ"
    "ay7tIIwBgD0AvVHQ74Sbj4W9bAZVD7E+OZ5DcAv6cwA6gK4nigu+8Ro4hOAi9E/8BMjbkbqY"
    "4eoavudiWDM46Wz6TGV46EVmZ0VAys5h82hVe1lTvMxeTl9B7VjBb1tFUx5XtLUW5VyHUCjI"
    "6sTUd3/LuzqXu5vayahC4oJSHOyONNUFC6ZJdVdLEaHQfeBNuL5Wd1yBKiRbXz/7YtOdgQcj"
    "fy6poqmW77iqbWXJe5J116C8vTkcjMdqg7WVxqZdQMNj8/28g5DXdl9p+xOTPWjq00BjPKyX"
    "lSqOo2Ca4AkfRVFgcaWQ/7IyCgNn/wEAtEQjQh+jurxSjdUEpbcdUZHID+8coAUxOLsb8LtG"
    "MZjS0FvJrE3L1LyN3AK/gFxcchH60N/Mv1rYkc+4g3/iETLfwLeNBlTNwFpzUeV5/Lc5Dqbk"
    "DbhpQ/L6/6Z+AN1Q55mg0CQcAAAAAElFTkSuQmCC")

